secrets:
  database_url: "postgresql://neondb_owner:npg_bnUiEAxH23Sm@ep-cold-mountain-ahrkqbkl-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"
  better_auth_secret: "B0B3h9iu5090BWXHfZ4yPLkLJzMO2rqr"
  openrouter_api_key: "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"
